import { Providers } from '@/providers';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import {Neuton} from 'next/font/google'
import './globals.css';
import { Sidebar } from '@/components/common/Sidebar';
import { twMerge } from 'tailwind-merge';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <div
            className={twMerge(
              `
            flex
            flex-row
            gap-2
            py-2
            mx-auto
            h-full
            `
            )}
          >
            <Sidebar />
            <div
              className={twMerge(
                `
                rounded-l-md
                overflow-hidden
                h-full
                w-full
                `
              )}
            >
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
